
import React from 'react';
import { MOCK_API_KEY_NOTE } from '../../constants';

const DocSection: React.FC<{ title: string; children: React.ReactNode; id?: string }> = ({ title, children, id }) => (
  <section id={id} className="mb-8 p-6 bg-slate-700 rounded-xl shadow-lg">
    <h2 className="text-2xl font-semibold text-cyan-400 mb-4 pb-2 border-b border-slate-600">{title}</h2>
    <div className="space-y-3 text-slate-300 leading-relaxed">
      {children}
    </div>
  </section>
);

const SubSection: React.FC<{ title: string; children: React.ReactNode; id?: string }> = ({ title, children, id }) => (
  <section id={id} className="mb-6 p-4 bg-slate-700/50 rounded-lg">
    <h3 className="text-xl font-semibold text-sky-400 mb-3">{title}</h3>
    <div className="space-y-2 text-slate-300">
      {children}
    </div>
  </section>
);

export const DocumentationView: React.FC = () => {
  return (
    <div className="space-y-6 max-w-4xl mx-auto">
      <header className="mb-8 text-center">
        <h1 className="text-4xl font-bold text-slate-100">SnagDef User Guide</h1>
        <p className="text-lg text-slate-400 mt-2">Your comprehensive guide to navigating and utilizing the SnagDef platform.</p>
      </header>

      <DocSection title="1. Introduction" id="intro">
        <p>Welcome to SnagDef, an autonomous threat detection and response system designed to provide robust security monitoring and management for your enterprise.</p>
        <p>This platform simulates the core functionalities of a modern cybersecurity solution, including various intelligent agents, real-time alert monitoring, and integrations with other security tools.</p>
        <p>This guide will walk you through each section of the SnagDef application: the Dashboard, Agents, Billing & Monetization, Integrations, and this Documentation section itself.</p>
      </DocSection>

      <DocSection title="2. Dashboard View" id="dashboard">
        <p>The Dashboard is your central hub for an at-a-glance overview of your organization's security posture.</p>
        <SubSection title="Key Metric Cards">
          <ul className="list-disc list-inside space-y-1">
            <li><strong>Critical Alerts:</strong> Total number of unresolved critical severity alerts.</li>
            <li><strong>High Priority Alerts:</strong> Total number of unresolved high severity alerts.</li>
            <li><strong>Incidents Resolved:</strong> Count of alerts that have been Contained or Resolved.</li>
            <li><strong>Active Agents:</strong> Number of agents currently in an active state (e.g., Scanning, Monitoring).</li>
          </ul>
        </SubSection>
        <SubSection title="Threat Trends Chart">
          <p>This chart visualizes the number of detected threats and found vulnerabilities over the last 7 days (simulated data). It helps in identifying patterns and potential increases in malicious activity.</p>
        </SubSection>
        <SubSection title="Recent Alerts">
          <p>A feed displaying the latest alerts generated by the system, prioritized by severity and timestamp. Clicking on an alert (future feature) would provide more details.</p>
        </SubSection>
      </DocSection>

      <DocSection title="3. Agents View" id="agents">
        <p>The Agents view allows you to manage and interact with the specialized security agents that form the core of SnagDef's capabilities.</p>
        <SubSection title="Understanding Agents">
          <p>Each agent performs a specific set of tasks:</p>
          <ul className="list-disc list-inside space-y-2">
            <li><strong>Recon Agent:</strong> Scans networks for vulnerabilities and maps potential attack surfaces. You can trigger a "Simulate Scan" action which will mimic a network scan and may generate new vulnerability alerts.</li>
            <li><strong>Threat Detection Agent:</strong> (Simulated) Uses Machine Learning to identify anomalies, malware signatures, and intrusion attempts. You can use the "Analyze Anomaly (AI)" feature to generate a sample threat analysis report using the Gemini API.</li>
            <li><strong>Incident Response Agent:</strong> Automates containment actions, such as isolating an infected device or blocking a malicious IP. The "Simulate Response" action demonstrates this by mimicking device isolation.</li>
            <li><strong>Forensics Agent:</strong> Logs detailed information about security incidents for post-mortem analysis and reporting. The "Generate Forensics Report (AI)" feature uses the Gemini API to create a sample detailed incident report.</li>
          </ul>
        </SubSection>
        <SubSection title="AI-Powered Reports (Gemini Integration)">
          <p>The "Analyze Anomaly (AI)" and "Generate Forensics Report (AI)" buttons on the Threat Detection and Forensics agent cards respectively, leverage the Google Gemini API to generate textual content.</p>
          <div className="p-3 bg-sky-600/20 text-sky-200 border border-sky-600 rounded-md my-2">
            <p className="font-semibold">Important: API Key Requirement</p>
            <p>{MOCK_API_KEY_NOTE}</p>
            <p>If an API key is not configured or is invalid, these features will display a message indicating unavailability, and the generated content might be a placeholder or an error notification.</p>
          </div>
        </SubSection>
      </DocSection>

      <DocSection title="4. Billing & Monetization View" id="billing">
        <p>This section provides an overview of your subscription, usage-based costs, and integration fees, helping you manage your SnagDef expenses.</p>
        <SubSection title="Subscription Plans">
          <p>SnagDef offers multiple subscription tiers (e.g., Basic, Pro, Enterprise), each with varying features and alert quotas. You can view details of each plan and switch your current subscription using the "Select Plan" buttons.</p>
        </SubSection>
        <SubSection title="Pay-Per-Alert Usage">
          <p>Some plans may include a "Pay-Per-Alert" model for critical alerts exceeding a certain quota. This card shows the number of critical alerts this month and the associated (simulated) cost.</p>
        </SubSection>
        <SubSection title="Monthly Cost Summary">
          <p>This card provides a consolidated view of your estimated monthly costs, including your base subscription fee, pay-per-alert charges, and fees for any active integrations.</p>
        </SubSection>
      </DocSection>

      <DocSection title="5. Integrations View" id="integrations">
        <p>SnagDef can integrate with various third-party Security Information and Event Management (SIEM) tools and other security platforms to enhance its capabilities and centralize security data.</p>
        <SubSection title="Available Integrations">
          <p>The view lists available integrations (e.g., Splunk, IBM QRadar, Microsoft Sentinel). Each card shows the integration's name, description, connection status, and any associated monthly fee.</p>
        </SubSection>
        <SubSection title="Connecting & Disconnecting">
          <p>Use the "Connect" or "Disconnect" button on each integration card to manage its status. Connecting an integration may incur additional fees, which will be reflected in your monthly cost summary.</p>
        </SubSection>
      </DocSection>

      <DocSection title="6. General Usage & Tips" id="usage-tips">
        <SubSection title="Navigation">
          <p>Use the sidebar on the left to navigate between the different views of the application: Dashboard, Agents, Billing, Integrations, and this Documentation.</p>
        </SubSection>
        <SubSection title="Alerts">
          <p>Alerts are color-coded by severity (Critical, High, Medium, Low, Info) to help you prioritize responses. The status of an alert indicates its current stage in the incident response lifecycle (New, Investigating, Contained, Resolved).</p>
        </SubSection>
      </DocSection>

      <DocSection title="7. Troubleshooting & FAQ" id="faq">
        <SubSection title="Q: Why are AI report generation features (e.g., 'Analyze Anomaly', 'Generate Forensics Report') not working or showing an error?">
          <p>A: These features depend on the Google Gemini API. For them to function correctly in a real environment, a valid API key must be configured as the <code>process.env.API_KEY</code> environment variable. In this simulation, if the key isn't present or if there's an issue with the (mocked or real) API call, the feature will be unavailable. Refer to the "AI-Powered Reports" section under "Agents View" in this guide for more details.</p>
        </SubSection>
        <SubSection title="Q: Is my data secure? What data is being collected?">
          <p>A: This SnagDef application is a front-end simulation. No real sensitive data is processed, transmitted to a live backend (beyond the Gemini API calls if a key is configured), or stored persistently. All interactions and data (like alerts and agent statuses) are maintained within your browser session for demonstration purposes only.</p>
        </SubSection>
         <SubSection title="Q: How often is the data on the dashboard updated?">
          <p>A: In this simulation, data like alerts and agent statuses are updated based on user interactions (e.g., simulating an agent action) or predefined mock data flows. The threat trends chart uses static sample data.</p>
        </SubSection>
      </DocSection>
      
      <DocSection title="8. About SnagDef" id="about">
        <p>SnagDef: Autonomous Security Platform (Simulation)</p>
        <p>Version: 1.0.0 (User Guide Updated: {new Date().toLocaleDateString()})</p>
        <p>This application is for demonstration and educational purposes to showcase UI/UX design and potential integration with AI services like Google Gemini for a cybersecurity product concept.</p>
      </DocSection>
    </div>
  );
};
